# Generated by Django 3.0.7 on 2020-07-26 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=140)),
                ('cover_image', models.ImageField(upload_to='blog/images')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('tags', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
