# Generated by Django 3.0.7 on 2020-07-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images'),
        ),
    ]
