# Generated by Django 3.0.7 on 2020-07-26 14:55

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200726_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='cover_image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='File name', max_length=80)),
                ('description', models.CharField(blank=True, default='File description', max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='blog/images/', validators=[blog.models.validate_image])),
                ('is_cover', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Entry')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='File name', max_length=80)),
                ('description', models.CharField(blank=True, default='File description', max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(default='Embed <iframe>')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='blog.Entry')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
