# Generated by Django 3.0.7 on 2020-07-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200726_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='File name', max_length=80)),
                ('description', models.CharField(blank=True, default='File description', max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(default='Embed <iframe>')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_embeds', to='blog.Entry')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='in_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Embed',
        ),
    ]
