# Generated by Django 3.0.7 on 2020-07-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='award',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='award',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
