# Generated by Django 3.0.7 on 2020-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200724_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='award',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
