# Generated by Django 3.0.7 on 2020-07-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200726_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-end_date']},
        ),
        migrations.RemoveField(
            model_name='education',
            name='thesis',
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Thesis', max_length=80)),
                ('title', models.CharField(default='Thesis Title', max_length=450)),
                ('pubfile', models.FileField(null=True, upload_to='pdf')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='about.Education')),
            ],
        ),
    ]
