# Generated by Django 3.0.7 on 2020-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200726_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='title',
        ),
        migrations.AddField(
            model_name='thesis',
            name='body',
            field=models.CharField(default='Thesis Place \n Thesis Title', max_length=450),
        ),
    ]
