# Generated by Django 3.0.7 on 2020-07-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_auto_20200726_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='place',
            field=models.CharField(blank=True, default='Thesis Place', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(default='Thesis Title', max_length=450),
        ),
    ]
