# Generated by Django 3.0.7 on 2020-07-24 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Publication Title', max_length=500)),
                ('journal', models.CharField(default='Journal, vol. X, pp. Y', max_length=300, null=True)),
                ('authors', models.CharField(default='D. Corona', max_length=400)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('url', models.CharField(max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
