# Generated by Django 3.0.7 on 2020-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pubfile',
            field=models.FileField(null=True, upload_to='images/publications/'),
        ),
    ]
